config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # get 'shopping/list'
  get "/general_shopping_list", to: 'shoppings#list'
  resources :publics, only: %i[index]
  resources :recipes, only: %i[index new create destroy show]
  resources :foods, only: %i[index new create destroy show]
  resources :recipe_foods, only: %i[index new create destroy show edit]

  get '/public_recipes', to: 'publics#index'
  root to: 'publics#index'
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order('created_at DESC')
  end

  def show; end

  def new
    @public = Public.new
  end

  def edit; end

  def create
    @public = Public.new(public_params)

    respond_to do |format|
      if @public.save
        format.html { redirect_to public_url(@public), notice: 'Public was successfully created.' }
        format.json { render :show, status: :created, location: @public }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @public.update(public_params)
        format.html { redirect_to public_url(@public), notice: 'Public was successfully updated.' }
        format.json { render :show, status: :ok, location: @public }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @public.destroy

    respond_to do |format|
      format.html { redirect_to publics_url, notice: 'Public was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_public
    @public = Public.find(params[:id])
  end

  def public_params
    params.fetch(:public, {})
  end
end

app/views/publics/_form.html.erb
<%= form_with(model: public) do |form| %>
  <% if public.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(public.errors.count, "error") %> prohibited this public from being saved:</h2>

      <ul>
        <% public.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publics/_public.html.erb
<div id="<%= dom_id public %>">
</div>

app/views/publics/edit.html.erb
<h1>Editing public</h1>

<%= render "form", public: @public %>

<br>

<div>
  <%= link_to "Show this public", @public %> |
  <%= link_to "Back to publics", publics_path %>
</div>

app/views/publics/index.html.erb
<section class="recipe-container">
<h1 class="text-center m-5 text-dark">Public Recipes</h1>
<div>
 <% @recipes.each do |recipe| %>
   <div class= "d-flex border border-dark m-5">
   <div class="m-3">
     <%= link_to recipe_path(recipe.id), class: "text-dark text-decoration-none", remote: :true do %>       
       <h2><%= recipe.name%></h2> 
       <h3> by: <%= recipe.user[:name] %> </h3>
     <% end %>
     </div>
   <div class="m-3">
      <h3>Total food Items: <%=Recipe.items(recipe.id)%></h3>
      <h3>Total Price: $<%=Recipe.total(recipe.id)%></h3>
   </div>

  </div>
  <% end %>
  </div>
</div>
</section>

app/views/publics/new.html.erb
<h1>New public</h1>

<%= render "form", public: @public %>

<br>

<div>
  <%= link_to "Back to publics", publics_path %>
</div>

app/views/publics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @public %>

<div>
  <%= link_to "Edit this public", edit_public_path(@public) %> |
  <%= link_to "Back to publics", publics_path %>
  <%= button_to "Destroy this public", @public, method: :delete %>
</div>