config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # get 'shopping/list'
  get "/general_shopping_list", to: 'shoppings#list'
  resources :publics, only: %i[index]
  resources :recipes, only: %i[index new create destroy show]
  resources :foods, only: %i[index new create destroy show]
  resources :recipe_foods, only: %i[index new create destroy show edit]

  get '/public_recipes', to: 'publics#index'
  root to: 'publics#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true

  def self.total(id)
    recipe = Recipe.find(id)
    recipe.recipe_foods.joins(:recipe, :food).sum('price * quantity')
  end

  def self.items(id)
    Recipe.find(id).recipe_foods.count
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @user = current_user
    @recipes = @user.recipes.includes(:recipe_foods)
    @foods = Food.all
  end

  def show
    @foods = Food.all
    @recipe_food = RecipeFood.new
    @recipe_foods = RecipeFood.where(recipe_id: params[:id])
  end

  def new
    @user = current_user
    @recipe = @user.recipes.new
  end

  def edit; end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:success] = 'Recipe created successfully'
          redirect_to recipes_url
        else
          flash.now[:error] = 'Error: Recipe could not be created'
          render :new
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = current_user
    @recipe = @user.recipes.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="m-5">
  <h2 class="text-center mb-3"><%= recipe.name %></h2>
  <div class="d-flex justify-content-between mb-3">
    <p>Preparation Time: <b><%= recipe.preparation_time %></b></p>
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
      <label class="form-check-label" for="flexSwitchCheckChecked">public</label>
    </div>
  </div>
  <div class="d-flex justify-content-between mb-3">
    <p>Cooking Time: <b><%= recipe.cooking_time %></b></p>
  </div>
  <div class="d-flex justify-content-between mb-3">
    <p>Steps: <b><%= recipe.description %></b></p>
  </div>
  <div class="d-flex justify-content-between mb-3">
    <%= button_to general_shopping_list_path(recipe.id) ,class: "btn btn-secondary", method: :get do%>
      Generate shopping list
    <% end %>
    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add ingredient</button>
  </div>
  <hr>
  <div class="d-flex justify-content-center">
    <table class="table w-75">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe_foods.each do |item| %>
        <tr>
          <th scope="row"><%= item.food.name %></th>
          <td><%= item.quantity %></td>
          <td>$<%= item.food.price*item.quantity %></td>
          <td><%= button_to "DELETE", item, method: :delete, class: 'btn btn-danger' %></td>
          <td><%= button_to "MODIFY", item, class: 'btn btn-primary', :disabled => true %></td>
        </tr>
        <% end %>


      </tbody>
    </table>

  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for (@recipe_food) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add ingredient</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <div class="d-flex justify-content-between">
          <%= form.hidden_field :recipe_id, :value => recipe.id %>
          <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]}, :prompt => 'Select One' %>
          <div class="form-group w-25">
            <%= form.number_field :quantity, step: 1,min: 1, placeholder: 'Qty', class: 'form-control' %>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Add", class: "btn btn-success w-25" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <h1>Your Recipes</h1>
  <% if current_user %>
    <%= link_to "New Recipe", new_recipe_path, class: "btn btn-primary align-self-end" %> <!-- No layout design, it will look better on navbar -->
    <% if @recipes.empty? %>
      <div>
        <h3 class="text-center">No recipes yet.</h3>
      </div>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="d-flex justify-content-center align-items-baseline gap-5 bg-light border w-75 m-auto p-3 my-3">
          <div class="d-flex flex-column align-items-center flex-grow-1">
            <h3 class="text-center"><%= link_to recipe.name, recipe_path(id: recipe.id), class: "text-dark" %></h3>
            <%= button_to "DELETE", recipe, method: :delete, class:"text-primary border-0" %>
          </div>
          <div class="flex-grow-1" style="max-height: 200px; overflow: auto">
            <p><%= recipe.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container contact">
	<div class="row">
		<div class="col-md-3">
			<div class="contact-info">
				<img class = "img-thumbnail" src="https://images.unsplash.com/photo-1542010589005-d1eacc3918f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmVjaXBlc3xlbnwwfHwwfHw%3D&w=1000&q=80" alt="image" />
				<h2>Add new Recipe</h2>
				<h4>You shoud love to try it!</h4>
			</div>
		</div>
		<div class="col-md-9">
         <%= form_with model: @recipe do |f| %>
			<div class="contact-form">
				<div class="form-group">
				  <%= f.label :name, class: "control-label col-sm-2" %> 
				<div class="col-sm-10">          
				  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name"%>
				  </div>
				</div>
				<div class="form-group">
				  <%= f.label :cooking_time,class: "control-label col-sm-2" %>
                <div class="col-sm-10">          
				  <%= f.text_field :cooking_time, class: "form-control"%>
				  </div>
				</div>
				<div class="form-group">
			      <%= f.label :preparation_time, class: "control-label col-sm-2" %>
				<div class="col-sm-10">
				  <%= f.text_field :preparation_time, class: "form-control"%>
				</div>
				</div>
                <div>
                <%= f.check_box :public%>
                <%= f.label :public %>
                </div>
				<div class="form-group">
				  <%= f.label :description, class: "control-label col-sm-2" %>
				  <div class="col-sm-10">
					<%= f.text_area :description, class: "form-control", rows: "5" %>
				  </div>
				</div>
				<div class="form-group">        
				  <div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-dark">Add Recipe</button>
				  </div>
          <% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <h1>Public Recipes</h1>
  <% if @recipes.empty? %>
    <h1>No public recipes yet.</h1>
  <% else %>
    <% @recipes.each do |recipe| %>
      <div class="d-flex justify-content-center align-items-baseline gap-5 bg-light border w-75 m-auto p-3 my-3">
        <div class="d-flex flex-column align-items-center flex-grow-1">
          <h3 class="text-center"><%= link_to recipe.name, recipe_path(id: recipe.id), class: "text-dark" %></h3>
          <p class="lead">By: <%= recipe.user.name %></p>
        </div>
        <div class="flex-grow-1" style="max-height: 200px; overflow: auto">
          <% total_food_items(recipe.id) %>
          <p class="lead">Total food items: <%= @sub_total[0] %></p>
          <p class="lead">Total price: $<%= @sub_total[1] %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="">
<%= render @recipe %>
</div>