config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # get 'shopping/list'
  get "/general_shopping_list", to: 'shoppings#list'
  resources :publics, only: %i[index]
  resources :recipes, only: %i[index new create destroy show]
  resources :foods, only: %i[index new create destroy show]
  resources :recipe_foods, only: %i[index new create destroy show edit]

  get '/public_recipes', to: 'publics#index'
  root to: 'publics#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    sign_out :user
    redirect_to
  end

  def new
    redirect_to user_session_path
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {})
  end
end

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
    <%= link_to 'My Recipes App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         
        <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Food List", foods_path, class: "nav-link" %>
        </li>
         
        <li class="nav-item">
          <%= link_to "My Recipes", recipes_path, class: "nav-link" %>
        </li>

         <li class="nav-item">
          <%= link_to "Shopping List", general_shopping_list_path, class: "nav-link" %>
        </li>

      
         <%= render 'shared/sign_in_out' %>
        
       
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>