config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # get 'shopping/list'
  get "/general_shopping_list", to: 'shoppings#list'
  resources :publics, only: %i[index]
  resources :recipes, only: %i[index new create destroy show]
  resources :foods, only: %i[index new create destroy show]
  resources :recipe_foods, only: %i[index new create destroy show edit]

  get '/public_recipes', to: 'publics#index'
  root to: 'publics#index'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }

  def self.value(id)
    recipe_food = RecipeFood.find(id)
    Food.find(recipe_food.food_id).price * recipe_food.quantity
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def show; end

  def new
    @recipe_food = RecipeFood.new
  end

  def edit; end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      format.html do
        if @recipe_food.save
          flash[:success] = 'Recipe created successfully'
          redirect_back_or_to({ action: 'show', id: params[:recipe_id] })
        else
          flash.now[:error] = 'Error: Recipe could not be created'
          render :new
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_back_or_to({ action: 'show', id: params[:recipe_id] }) }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.fetch(:recipe_food, {}).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
</div>

app/views/recipe_foods/edit.html.erb
<div class="container d-flex flex-column align-items-center">
  <h2>Edit food quantity for recipe:</h2>
  <%= form_with(model: @recipe_food, url: recipe_recipe_food_path, method: "patch") do |form| %>

    <div class="form-group mb-3">
      <%= form.label :quantity %> <br>
      <%= form.number_field :quantity, class: "form-control" , required: true %>
    </div>

    <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="container d-flex flex-column align-items-center">
  
    <h2>Add new food to recipe:</h2>
    <%= form_with url: recipe_recipe_foods_path do |form| %>
      <%= select("food", "food_id", Food.all.collect { |p| [ p.name, p.id ] }, { prompt: 'Select Food' }) %>

      <div class="form-group mb-3">
        <%= form.label :quantity %> <br>
        <%= form.number_field :quantity, class: "form-control" , required: true %>
      </div>

      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    
  <% end %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>